---
# tasks file for aws-ec2
#
- name: "k8s-master"
  ec2:
          count: 1
          image: "{{ amiimageid }}"
          instance_type: t2.micro
          region: "{{ region }}"
          instance_tags:
                  Name: master
          group_id: "{{ securitygrpid }}"
          key_name: "{{ key }}"
          aws_access_key: "{{ access_key }}"
          aws_secret_key: "{{ secret_key }}"
          state: present
          wait: yes

- name: "k8s-worker"
  ec2:
          count: "{{ workernodes }}"
          image: "{{ amiimageid }}"
          instance_type: t2.micro
          region: "ap-south-1"
          instance_tags:
             Name: worker
          group_id: "{{ securitygrpid }}"
          key_name: "{{ key }}"
          state: present
          aws_access_key: "{{ access_key }}"
          aws_secret_key: "{{ secret_key }}"
          state: present
          wait: yes
        


