- hosts: tag_Name_master
  roles:
  - k8s-master


- hosts: tag_Name_worker
  vars_prompt: 
  - name: "master_token"
    prompt: "Enter token to join to master: "
    private: no
  roles:
  - k8s-worker

- hosts: "tag_Name_master"
  roles:
       - name: "Launching Wordpress and Mysql"
         role: "sql-wordpress"
